config/routes.rb
Rails.application.routes.draw do

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    get "/sites/:key", to: "sites#index"
    get "/sites/:key/new", to: "sites#new"
    post "/sites/:key", to: "sites#create", as: :site_create
    post "/sites/:key/publish", to: "sites#publish", as: :site_publish

    get "/hirefire/:key/info", to: "hirefire#queue"

    root "administrators#index"
    get "/administrators", to: redirect("/")
    resources :administrators

    resources :contests

end

app/controllers/contests_controller.rb
require 'will_paginate/array'

class ContestsController < ApplicationController

    include AwsHelper

    before_action :set_contest, only: [:show, :edit, :update, :destroy]
    before_action :authorize

    # GET /contests
    def index
        @contests = Contest.where(administrator_id: current_user.id).order(created_at: :desc)
    end

    # GET /contests/1
    def show
        @voices = Voice.where(contest_id: @contest.id)
            .order_by(:created_at => 'desc')
            .paginate(:page => params[:page], :per_page => 50)
    end

    # GET /contests/new
    def new
        @contest = Contest.new
    end

    # GET /contests/1/edit
    def edit
    end

    # POST /contests
    def create
        @contest = Contest.new(contest_params)
        @contest.administrator = current_user
        sy = contest_params["start_date(1i)"].to_i
        sm = contest_params["start_date(2i)"].to_i
        sd = contest_params["start_date(3i)"].to_i
        @contest.start_date = Date.new(sy, sm, sd)
        ey = contest_params["end_date(1i)"].to_i
        em = contest_params["end_date(2i)"].to_i
        ed = contest_params["end_date(3i)"].to_i
        @contest.end_date = Date.new(ey, em, ed)
        @contest.created_at = DateTime.now()
        respond_to do |format|
            if @contest.save
                format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    # PATCH/PUT /contests/1
    def update
        respond_to do |format|
            @contest.name = contest_params[:name]
            @contest.image = contest_params[:image]
            @contest.url = contest_params[:url]
            sy = contest_params["start_date(1i)"].to_i
            sm = contest_params["start_date(2i)"].to_i
            sd = contest_params["start_date(3i)"].to_i
            @contest.start_date = Date.new(sy, sm, sd)
            ey = contest_params["end_date(1i)"].to_i
            em = contest_params["end_date(2i)"].to_i
            ed = contest_params["end_date(3i)"].to_i
            @contest.end_date = Date.new(ey, em, ed)
            @contest.reward = contest_params[:reward]
            @contest.script = contest_params[:script]
            @contest.recomendations = contest_params[:recomendations]
            if @contest.save()
                format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end

    # DELETE /contests/1
    def destroy
        s3 = s3_client 
        delete_s3(s3, "#{@contest.id}/")
        @contest.destroy
        respond_to do |format|
            format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
        end
    end

    private
    def set_contest
        @contest = Contest.find(params[:id])
    end

    def contest_params
        params.require(:contest).permit(:name, :image, :url, :start_date, :end_date, :reward, :script, :recomendations)
    end

end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(contest) do |f| %>
  <% if contest.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= request.base_url %>/sites/<%= f.text_field :url, size: 5 %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :reward %>
    <%= f.number_field :reward %>
  </div>

  <div class="field">
    <%= f.label :script %>
    <%= f.text_area :script %>
  </div>

  <div class="field">
    <%= f.label :recomendations %>
    <%= f.text_area :recomendations %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Site</th>
      <th>Start</th>
      <th>End</th>
      <th>Reward</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <% url_contest = request.base_url + "/sites/" + contest.url %>  
      <tr>
        <td><%= contest.name %></td>
        <td><a href="<%= url_contest %>" target="_blank"><%= contest.url %></a></td>
        <td><%= contest.start_date %></td>
        <td><%= contest.end_date %></td>
        <td><%= contest.reward %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @contest.name %>
</p>

<p>
<strong>Image:</strong>
<%= image_tag(@contest.image, width: 600) if @contest.image.present? %>
</p>

<p>
<% url_contest = request.base_url + "/sites/" + @contest.url %>  
<strong>Url:</strong>
<a href="<%= url_contest %>" target="_blank"><%= url_contest %></a>
</p>

<p>
<strong>Start:</strong>
<%= @contest.start_date %>
</p>

<p>
<strong>End:</strong>
<%= @contest.end_date %>
</p>

<p>
<strong>Reward:</strong>
<%= @contest.reward %>
</p>

<p>
<strong>Script:</strong>
<%= @contest.script %>
</p>

<p>
<strong>Recomendations:</strong>
<%= @contest.recomendations %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> 

<h1>Voices</h1>

<table>
    <thead>
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Last name</th>
            <th>Created</th>
            <th>Status</th>
            <th>Message</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Play</th>
        </tr>
    </thead>

    <tbody>
        <% @voices.each do |voice| %>
            <% source_url = (voice.source_url) ? voice.source_url.url : "#" %>
            <% source_file = (voice.source_url) ? voice.source_url_identifier : "" %>
            <% done, destination_url, destination_file = converted_voice(voice) %>
            <tr>
                <td><%= voice.email %></td>
                <td><%= voice.name %></td>
                <td><%= voice.last_name %></td>
                <td><%= voice.created_at %></td>
                <td><%= done ? "Converted" : "In Progress" %></td>
                <td><%= voice.message %></td>
                <td>
                    <a href="<%= source_url %>" download="<%= source_file %>">
                        <%= source_file %>
                    </a>
                </td>
                <td>
                    <a href="<%= destination_url %>" download="<%= destination_file %>">
                        <%= destination_file %>
                    </a>
                </td>
                <td>
                    <audio controls>
                        <source src="<%= destination_url %>" type="audio/mpeg"> 
                            Your browser does not support the audio element.
                    </audio>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= page_entries_info @voices %>
<br />
<%= will_paginate @voices %>
<br />
<%= link_to 'Back', contests_path %>