config/routes.rb
Rails.application.routes.draw do

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    get "/sites/:key", to: "sites#index"
    get "/sites/:key/new", to: "sites#new"
    post "/sites/:key", to: "sites#create", as: :site_create
    post "/sites/:key/publish", to: "sites#publish", as: :site_publish

    get "/hirefire/:key/info", to: "hirefire#queue"

    root "administrators#index"
    get "/administrators", to: redirect("/")
    resources :administrators

    resources :contests

end

app/models/administrator.rb
class Administrator

    include Mongoid::Document
    include ActiveModel::SecurePassword 
    include Mongoid::Attributes::Dynamic
    
    field :name, type: String
    field :last_name, type: String
    field :email, type: String
    field :password_digest, type: String
    field :created_at, type: DateTime

    has_secure_password
    has_many :contests, :dependent => :delete_all 

    validates :name, presence: true
    validates :last_name, presence: true
    validates :email, uniqueness: true, email: true
    validates :password, presence: true
    validates_confirmation_of :password, message: 'should match'
    
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
    before_action :set_administrator, only: [:show, :edit, :update]
    before_action :authorize, only: [:show, :edit, :update]

    # GET /administrators
    def index
        if current_user
            redirect_to '/contests'
        end
    end

    # GET /administrators/1
    def show
    end

    # GET /administrators/new
    def new
        @administrator = Administrator.new
    end

    # GET /administrators/1/edit
    def edit
    end

    # POST /administrators
    def create
        @administrator = Administrator.new(administrator_params)
        @administrator.created_at = DateTime.now()
        respond_to do |format|
            if @administrator.save
                format.html { redirect_to '/', notice: 'Administrator was successfully created. Please login' }
            else
                format.html { render :new }
            end
        end
    end

    # PATCH/PUT /administrators/1
    def update
        respond_to do |format|
            if @administrator.update(administrator_params)
                format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
        @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
        params.require(:administrator).permit(:name, :last_name, :email, :password, :password_confirmation)
    end

end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(administrator) do |f| %>

  <h2 class="new_administrator-heading">New Administrator</h2>

  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: 'sr-only' %>
    <%= f.text_field :name, :class => 'form-control top', :placeholder => 'Name' %>
  </div>

  <div class="field">
    <%= f.label :last_name, class: 'sr-only' %>
    <%= f.text_field :last_name, :class => 'form-control middle', :placeholder => 'Last name' %>
  </div>

  <div class="field">
    <%= f.label :email, class: 'sr-only' %>
    <%= f.text_field :email, :class => 'form-control middle', :placeholder => 'Email' %>
  </div>

  <div class="field">
    <%= f.label :password, class: 'sr-only' %>
    <%= f.password_field :password, :class => 'form-control middle', :placeholder => 'Password' %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, class: 'sr-only' %>
    <%= f.password_field :password_confirmation, :class => 'form-control bottom', :placeholder => 'Confirm password' %>
  </div>

  <br />

  <div class="actions">
    <!-- <%= f.submit %> -->
    <%= submit_tag("Register", :class => 'btn btn-lg btn-primary btn-block') %>
  </div>

  <br />
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render "form", administrator: @administrator %>

<%= link_to "Back", "/contests"%>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
    <h1>Get a perfect voice</h1>
    <p class="lead">Easily perform contests to find the best voices for your advertisement.</p>
    <p><a class="btn btn-lg btn-success" href="administrators/new" role="button">Sign up today</a></p>
</div>

<div class="row marketing">
    <div class="col-lg-6">
        <h4>Want to submit a contest?</h4>
        <p>Get voice actors to audition for your project, from pros to amateurs.</p>

        <h4>Honest and transparent pricing</h4>
        <p>All voice overs are backed by our 100% satisfaction guarantee.</p>

        <h4>Scale</h4>
        <p>Scale a high volume of voice overs reliably and affordably.</p>
    </div>

    <div class="col-lg-6">
        <h4>One format to hear em' all</h4>
        <p>Every voice file uploaded to a contest is automatically converted to MP3.</p>

        <h4>Reach the globe</h4>
        <p>Anyone can participate on your contest, don't even need to make an account registration.</p>

        <h4>Don't wait</h4>
        <p>Every file conversion and email notification is done on the background, what you get is ready to be used!.</p>
    </div>
</div>

app/views/administrators/new.html.erb
<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', '/' %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @administrator.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @administrator.email %>
</p>

<% if current_user %>
    <%= link_to 'Back', "/contests" %>
<% else %>
    <%= link_to 'Back', administrators_path %>
<% end %>