config/routes.rb
Rails.application.routes.draw do

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    get "/sites/:key", to: "sites#index"
    get "/sites/:key/new", to: "sites#new"
    post "/sites/:key", to: "sites#create", as: :site_create
    post "/sites/:key/publish", to: "sites#publish", as: :site_publish

    get "/hirefire/:key/info", to: "hirefire#queue"

    root "administrators#index"
    get "/administrators", to: redirect("/")
    resources :administrators

    resources :contests

end

app/controllers/sites_controller.rb
require 'will_paginate/array'
require 'json'

class SitesController < ApplicationController

	include AwsHelper
	include RabbitHelper

	before_action :set_contest 

	def get_message
		return 'We have received your voice and we are processing it so that it can ' + 
			'be published in the page of the contest and can be later reviewed by ' + 
			'our team. As soon as the voice is published in the contest page we ' + 
			'will notify you by email.'
	end

	# GET /sites/:key
	def index 
		@voices = Voice.where(contest_id: @contest.id)
			.order_by(:created_at => 'desc')
			.paginate(:page => params[:page], :per_page => 20)
		render layout: "application_site"
	end

	# GET /sites/:key/new
	def new
		@voice = Voice.new
		response.headers['X-Csrf-Token'] = form_authenticity_token
		render layout: "application_site"
	end

	# POST /sites/:key
	def create
		@voice = Voice.new(voice_params)
		@voice.contest = @contest
		@voice.created_at = DateTime.now()
		@voice.converted = false
		respond_to do |format|
			if @voice.save
				queue_voice_message(@voice.id.to_s, File.basename(@voice.source_url.file.path), @voice.email, @voice.contest.id.to_s, @voice.contest.url)
				format.html { redirect_to "/sites/" + @contest.url, notice: get_message }
			else
				format.html { render :new, layout: "application_site" }
			end
		end
	end

	# POST /sites/:key/publish
	def publish
		params = publish_params
		queue_voice_message(params["id"], params["name"], params["email"], params["contest_id"], params["contest"])
		render status: 200, json: { publish: true }
	end
	
	def queue_voice_message(id, name, email, contest_id, contest) 
		message = {
			'id' => id,
			'name' => name,
			'email' => email,
			'contest_id' => contest_id,
			'contest' => contest
		}
		rmq_connect
		rmq_publish(JSON[message])
		rmq_disconnect
	end

	private
	def set_contest
		@contest = Contest.find_by(url: params[:key])
	end

	def voice_params
		params.require(:voice).permit(:email, :name, :last_name, :message, :source_url)
	end

	def publish_params
		return JSON.parse(request.body.read)
	end

end

app/helpers/sites_helper.rb
module SitesHelper

    def my_page_entries_info(collection, n, options = {})
        entry_name = options[:entry_name] || (collection.empty?? 'item' :
                                              collection.first.class.name.split('::').last.titleize)
        if (collection.total_pages - n) < 2
            case collection.size
            when 0; "No #{entry_name.pluralize} found"
            else; "Displaying all #{entry_name.pluralize}"
            end
        else
            %{Displaying %d - %d of %d #{entry_name.pluralize}} % [
                collection.offset + 1,
                collection.offset + collection.length,
                (collection.total_entries - n)
            ]
        end
    end

end

app/views/sites/_form.html.erb
<%= form_for voice, url: site_create_path(@contest.url) do |f| %>
    <% if voice.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(voice.errors.count, "error") %> prohibited this voice from being saved:</h2>

            <ul>
                <% voice.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
        <%= f.label :message %>
        <%= f.text_area :message %>
    </div>

    <div class="field">
        <%= f.label :source_url %>
        <%= f.file_field :source_url %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/sites/index.html.erb
<div class="header clearfix">
    <%= image_tag(@contest.image, width: 600) if @contest.image.present? %>
</div>

<h2 class="text-muted"><%= @contest.name %></h2>

<p>
<strong>Start:</strong>
<%= @contest.start_date %>
</p>

<p>
<strong>End:</strong>
<%= @contest.end_date %>
</p>

<p>
<strong>Reward:</strong>
<%= @contest.reward %>
</p>

<p>
<strong>Script:</strong>
<%= @contest.script %>
</p>

<p>
<strong>Recomendations:</strong>
<%= @contest.recomendations %>
</p>

<%= link_to 'New Voice', '/sites/'+@contest.url+'/new' %>
<br />
<p id="notice"><%= notice %></p>

<h3 class="text-muted">Voices</h3>

<table>
    <thead>
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Last name</th>
            <th>Message</th>
            <th>Voice</th>
        </tr>
    </thead>

    <tbody>
        <% n = 0 %>
        <% @voices.each do |voice| %>
            <% done, destination_url, destination_file = converted_voice(voice) %>
            <% 
            if ! done 
                n = n + 1
                next 
            end 
            %>
            <tr>
                <td><%= voice.email %></td>
                <td><%= voice.name %></td>
                <td><%= voice.last_name %></td>
                <td><%= voice.message %></td>
                <td>
                    <audio controls>
                        <source src="<%= destination_url %>" type="audio/mpeg"> 
                            Your browser does not support the audio element.
                    </audio>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= my_page_entries_info(@voices, n) %>
<br />
<%= will_paginate @voices %>
<br />

app/views/sites/new.html.erb
<div class="header clearfix">
    <%= image_tag(@contest.image, width: 600) if @contest.image.present? %>
</div>

<h1>New Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Back', '/sites/'+@contest.url %>